swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /mul_values:
    get:
      operationId: "fibonaci.fibonacci_range"
      tags:
        - "Mul_value"
      summary: "Given an index, this function return the range of Fibonacci functions up to and including the given index"
      description: "Read given index"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "n"
        #default: 4
        in: "query"
        description: "Tags to filter by"
        required: false
        type: "integer"
        items:
          type: "integer"
        collectionFormat: "multi"
      responses:
          200:
              description: "successful operation"
              schema:
                  type: "array"
          400:
              description: "Invalid status value"




